//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaloniaWinUI.ColorPicker {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AvaloniaWinUI.ColorPicker.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ContentHSVComboBoxItem {
            get {
                return ResourceManager.GetString("ContentHSVComboBoxItem", resourceCulture);
            }
        }
        
        internal static string ContentRGBComboBoxItem {
            get {
                return ResourceManager.GetString("ContentRGBComboBoxItem", resourceCulture);
            }
        }
        
        internal static string HelpTextColorSpectrum {
            get {
                return ResourceManager.GetString("HelpTextColorSpectrum", resourceCulture);
            }
        }
        
        internal static string HelpTextMoreButton {
            get {
                return ResourceManager.GetString("HelpTextMoreButton", resourceCulture);
            }
        }
        
        internal static string LocalizedControlTypeColorSpectrum {
            get {
                return ResourceManager.GetString("LocalizedControlTypeColorSpectrum", resourceCulture);
            }
        }
        
        internal static string TextAlphaLabel {
            get {
                return ResourceManager.GetString("TextAlphaLabel", resourceCulture);
            }
        }
        
        internal static string TextBlueLabel {
            get {
                return ResourceManager.GetString("TextBlueLabel", resourceCulture);
            }
        }
        
        internal static string TextGreenLabel {
            get {
                return ResourceManager.GetString("TextGreenLabel", resourceCulture);
            }
        }
        
        internal static string TextHueLabel {
            get {
                return ResourceManager.GetString("TextHueLabel", resourceCulture);
            }
        }
        
        internal static string TextMoreButtonLabelCollapsed {
            get {
                return ResourceManager.GetString("TextMoreButtonLabelCollapsed", resourceCulture);
            }
        }
        
        internal static string TextMoreButtonLabelExpanded {
            get {
                return ResourceManager.GetString("TextMoreButtonLabelExpanded", resourceCulture);
            }
        }
        
        internal static string TextRedLabel {
            get {
                return ResourceManager.GetString("TextRedLabel", resourceCulture);
            }
        }
        
        internal static string TextSaturationLabel {
            get {
                return ResourceManager.GetString("TextSaturationLabel", resourceCulture);
            }
        }
        
        internal static string TextValueLabel {
            get {
                return ResourceManager.GetString("TextValueLabel", resourceCulture);
            }
        }
        
        internal static string ToolTipStringAlphaSlider {
            get {
                return ResourceManager.GetString("ToolTipStringAlphaSlider", resourceCulture);
            }
        }
        
        internal static string ToolTipStringHueSliderWithColorName {
            get {
                return ResourceManager.GetString("ToolTipStringHueSliderWithColorName", resourceCulture);
            }
        }
        
        internal static string ToolTipStringHueSliderWithoutColorName {
            get {
                return ResourceManager.GetString("ToolTipStringHueSliderWithoutColorName", resourceCulture);
            }
        }
        
        internal static string ToolTipStringSaturationSliderWithColorName {
            get {
                return ResourceManager.GetString("ToolTipStringSaturationSliderWithColorName", resourceCulture);
            }
        }
        
        internal static string ToolTipStringSaturationSliderWithoutColorName {
            get {
                return ResourceManager.GetString("ToolTipStringSaturationSliderWithoutColorName", resourceCulture);
            }
        }
        
        internal static string ToolTipStringValueSliderWithColorName {
            get {
                return ResourceManager.GetString("ToolTipStringValueSliderWithColorName", resourceCulture);
            }
        }
        
        internal static string ToolTipStringValueSliderWithoutColorName {
            get {
                return ResourceManager.GetString("ToolTipStringValueSliderWithoutColorName", resourceCulture);
            }
        }
        
        internal static string ValueStringColorSpectrumWithColorName {
            get {
                return ResourceManager.GetString("ValueStringColorSpectrumWithColorName", resourceCulture);
            }
        }
        
        internal static string ValueStringColorSpectrumWithoutColorName {
            get {
                return ResourceManager.GetString("ValueStringColorSpectrumWithoutColorName", resourceCulture);
            }
        }
        
        internal static string ValueStringHueSliderWithColorName {
            get {
                return ResourceManager.GetString("ValueStringHueSliderWithColorName", resourceCulture);
            }
        }
        
        internal static string ValueStringHueSliderWithoutColorName {
            get {
                return ResourceManager.GetString("ValueStringHueSliderWithoutColorName", resourceCulture);
            }
        }
        
        internal static string ValueStringSaturationSliderWithColorName {
            get {
                return ResourceManager.GetString("ValueStringSaturationSliderWithColorName", resourceCulture);
            }
        }
        
        internal static string ValueStringSaturationSliderWithoutColorName {
            get {
                return ResourceManager.GetString("ValueStringSaturationSliderWithoutColorName", resourceCulture);
            }
        }
        
        internal static string ValueStringValueSliderWithColorName {
            get {
                return ResourceManager.GetString("ValueStringValueSliderWithColorName", resourceCulture);
            }
        }
        
        internal static string ValueStringValueSliderWithoutColorName {
            get {
                return ResourceManager.GetString("ValueStringValueSliderWithoutColorName", resourceCulture);
            }
        }
    }
}
